### PR TITLE
Added herocard to keyboard support

### PR DESCRIPTION
**Pull request by austinhuang0131**
As a response to #1. It should look like how Kik supports hero cards.

### CODE REVIEW

**Comment by austinhuang0131** [comment]
Also fixed your package.json cuz npm doesn't auto-install devDependencies

**Comment by alexsorokoletov** [comment]
@austinhuang0131 looks good to me, do you have any example handy how a hero card looks in Skype, FB and Viber correspondingly?

**Comment by austinhuang0131** [comment]
https://docs.botframework.com/en-us/channel-inspector/channels/Skype/

**Comment by alexsorokoletov** [comment]
@austinhuang0131 Austin when you have a chance, I'd like to see how hero card from standard channels will render now in Viber, that's it.

Attach a screenshot from your test scenario, I will check it and we will merge and update the npm package. 

I appreciate both the improvement and fixes. 👍

**Comment by alexsorokoletov** [comment]
@austinhuang0131 waiting here for a screenshot from your side to make sure everything looks just fine. 

https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests

**Comment by austinhuang0131** [comment]
which I'll have to solve #3 first

**Comment by alexsorokoletov** [comment]
@austinhuang0131 do you need any help with #3? I thought you're no longer interested in it

**Pull request closed without merging**
